# Generated by Django 3.0.6 on 2020-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('condition', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
