# Generated by Django 2.2.10 on 2020-07-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mobile',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
